# -*- coding: utf-8 -*-
{
	'name': 'Kernel Backend Theme',

	'summary': '',

	'description': """
Best Odoo Backend Themes,
        Kernal Backend Theme,
        Theme Kernal,
        Backend Theme Kernal,
        Odoo Kernal Theme,
        Odoo Kernal Backend Theme,
        User Configurable Theme,
        User Configurable Backend Theme,
        User Friendly Backend Theme,
        User Friendly Theme,
        Theme for Backend,
        Themes for Odoo Backend,
        Best Backend Themes,
        Odoo Theme for Backend,
        Odoo Website Themes,
        Odoo Themes,
        Odoo Backend Themes,
        Backend Themes,
        eCommerce Website Themes,
        E-commerce Backend Theme,
        Themes For Odoo Websites,
        Store Themes,
        Attractive Theme For eCommerce,
        Stylish Theme for eCommerce,
        Favorite Menu Themes,
        Advance theme configuration,
        Fully Responsive backend theme,
        User friendly search view ,
        User specific backend theme,
        Company specific backend theme,
        Dark mode backend theme,
        Login page background image theme,
        Vertical top menus Themes,
        Horizontal top menus Themes,
        Advance search Themes,
        menu items themes,
        Enterprise Theme,
        Community Theme,
        Enterprise Theme,
        Best Odoo Theme,
        Odoo Enterprise Theme,
        Odoo Community Theme,
        Dynamic Theme,
        Dynamic Backend Theme,
        Fuzzy Search Option Backend Theme,
        Autoload Backend Themes,
        Single Click App Navigation Theme,
        Dynamic Color Setting Theme,
        Advance System Tray Menu Theme,
        Odoo Business Themes,
        Odoo Corporate Themes,
        Odoo Corporate Backend Themes,
        Customized Themes,
        Customized Backend Themes,
        Customized Odoo Themes,
        backend theme,
        odoo backend theme,
        enterprise backend theme,
        kanban view,
        responsive backend theme,
        backend theme global,
        backend theme community edition
        top backend theme,
        best backend theme,
        bcend theme,
""",

	'author': 'Ksolves India Ltd.',

	'website': 'https://store.ksolves.com/',

	'license': 'OPL-1',

	'currency': 'EUR',

	'price': '210',

	'version': '1.1.4',

	'live_test_url': 'https://themekernel.kappso.com/web/demo_login',

	'category': 'Themes/Backend',

	'support': 'sales@ksolves.com',

	'depends': ['base', 'web', 'base_setup', 'web_editor'],
        'assets': {
        'web.assets_backend': [
            "ks_theme_kernel/static/src/scss/ks_appdrawer_only_for_background_image.scss",
            "ks_theme_kernel/static/src/css/style.css",
            "ks_theme_kernel/static/src/scss/variables.scss",
            "ks_theme_kernel/static/src/scss/ks_animation.scss",
            "ks_theme_kernel/static/src/scss/ks_common.scss",
            "ks_theme_kernel/static/src/scss/ks_background.scss",
            "ks_theme_kernel/static/src/scss/ks_left_sidebar.scss",
            "ks_theme_kernel/static/src/scss/ks_filter.scss",
            "ks_theme_kernel/static/src/scss/ks_btn.scss",
            "ks_theme_kernel/static/src/scss/ks_views.scss",
            "ks_theme_kernel/static/src/scss/ks_color_palettes.scss",
            "ks_theme_kernel/static/src/scss/ks_navbar.scss",
             "ks_theme_kernel/static/src/scss/ks_override.scss",
            "ks_theme_kernel/static/src/scss/compatibility/lvm.scss",
            "ks_theme_kernel/static/src/scss/ks_settings_menu.scss",
            "ks_theme_kernel/static/src/scss/ks_rtl.scss",
            "ks_theme_kernel/static/src/easy-autocomplete/easy-autocomplete.css",
            "ks_theme_kernel/static/src/spectrum/spectrum.css",
            "ks_theme_kernel/static/src/scss/ks_color_fixes.scss",
            "ks_theme_kernel/static/src/js/ks_inherit_menu.js",
            "ks_theme_kernel/static/src/easy-autocomplete/easy-autocomplete.js",
            "ks_theme_kernel/static/src/spectrum/spectrum.js",
            "ks_theme_kernel/static/src/js/ks_configuration.js",
            "ks_theme_kernel/static/src/js/ks_configuration_widget.js",
            "ks_theme_kernel/static/src/js/ks_search_bar_into_header.js",
            "ks_theme_kernel/static/src/js/ks_font_icon_widget.js",
            "ks_theme_kernel/static/src/js/ks_special_icons_widget.js",
            "ks_theme_kernel/static/src/js/ks_unsplash_widget.js",
            "ks_theme_kernel/static/src/js/ks_clock_widget.js",
            "ks_theme_kernel/static/src/js/ks_list_render.js",
            "ks_theme_kernel/static/src/scss/themes/default_color.scss",
            "ks_theme_kernel/static/src/js/ks_click_form_edit.js",
            "ks_theme_kernel/static/src/scss/themes/color_1.scss",
            "ks_theme_kernel/static/src/scss/themes/color_2.scss",
            "ks_theme_kernel/static/src/scss/themes/color_3.scss",
            "ks_theme_kernel/static/src/scss/themes/color_4.scss",
            "ks_theme_kernel/static/src/scss/themes/color_5.scss",
            'ks_theme_kernel/static/src/scss/themes/color_6.scss',
            "ks_theme_kernel/static/src/scss/themes/color_7.scss",
            "ks_theme_kernel/static/src/scss/themes/color_8.scss",
            "ks_theme_kernel/static/src/scss/themes/color_9.scss",
            'ks_theme_kernel/static/src/scss/themes/color_10.scss',
            "ks_theme_kernel/static/src/scss/themes/dark_mode.scss",
            "ks_theme_kernel/static/src/scss/fonts/font_1.scss",
            "ks_theme_kernel/static/src/scss/fonts/font_2.scss",
            "ks_theme_kernel/static/src/scss/fonts/font_3.scss",
            "ks_theme_kernel/static/src/scss/fonts/font_4.scss",
            "ks_theme_kernel/static/src/scss/fonts/font_5.scss",
            "ks_theme_kernel/static/src/scss/fonts/font_6.scss",
            "ks_theme_kernel/static/src/scss/fonts/font_7.scss",
            'ks_theme_kernel/static/src/xml/ks_home_click_widget.xml', 
            'ks_theme_kernel/static/src/xml/ks_configuration.xml', 
            'ks_theme_kernel/static/src/xml/ks_clock.xml', 
            'ks_theme_kernel/static/src/xml/ks_icon_widgets.xml'


        ],
        'web.assets_frontend': [
            "ks_theme_kernel/static/src/scss/ks_login_page.scss",
        ],
    },

	'data': [
                'wizard/ks_menu_icon_views.xml', 
                # 'views/ks_theme_setting.xml',
                # 'security/ir.model.access.csv', 
                # 'data/ks_record.xml', 
                # 'views/ks_app_sidebar.xml', 
                # 'views/ks_user_preferences_views.xml'
                ],

	'qweb': [],

	'images': ['static/description/ks_theme_kernel_inner.png', 'static/description/list_screenshot.gif'],

	'application': True,

	'installable': True,
}
